
development:
  secret_key_base: 9d7863151f94dd295eaf125a6bcf33386676b4e73475a55a50eb574a2b3cbc20a8c13071979261d66d76729cd49742e8b725d1e0929eb4b976f72d530c85199e

  
test:
  secret_key_base: 2963815850e6542bbdefa7981fe9ded6cbc4076ed3ff551c4806f23921c625f54a6484dcbe1c682716c41ae743f6de714c1574421daa53bc91f54e2bab72dd76


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
